dist: trusty

sudo: required

language: node_js

node_js:
  - node
  - '9'
  - '8'

cache: node_modules

addons:
  ssh_known_hosts: "linux.cs.pdx.edu"

before_script:
# Start up chrome headless
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test

before_deploy:
  # Unpack ssh key to /tmp so we can connect without a password
  - openssl aes-256-cbc -K $encrypted_70fbc6f46be6_key -iv $encrypted_70fbc6f46be6_iv -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d

  # Add key to ssh keyring
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_deploy_rsa
  - ssh-add /tmp/travis_deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: "npm build && rsync -avz -r --delete-after --quiet -e ssh $TRAVIS_BUILD_DIR/dist gomenas@linux.cs.pdx.edu:/u/gomenas/Documents/frupal/ && [ $? != 0 ]; then exit 1"
  on:
    branch: sgomena/dev

