dist: xenial

sudo: required

language: node_js

node_js:
  - node
  - '9'
  - '8'

install:
  - "npm install"

jobs:
  include:
    - stage: "Build"
      name: "Build with Parcel"
      script: "npm build"

    - stage: "Test"
      name: "Run unit tests with mocha"

      node_js:
        - node  # Latest
        - '8'

      before_script:
        # Start up chrome headless
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      script: "npm test"

    - stage: deploy
      name: "Deploy to linux.cs.pdx.edu"

      before_deploy:
        # Unpack ssh key to /tmp so we can connect without a password
        - openssl aes-256-cbc -K $encrypted_70fbc6f46be6_key -iv $encrypted_70fbc6f46be6_iv -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d

        # Add key to ssh keyring
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/travis_deploy_rsa
        - ssh-add /tmp/travis_deploy_rsa

      provider: script
      script: "rsync -avz -r --delete-after --quiet -e ssh $TRAVIS_BUILD_DIR/dist gomenas@linux.cs.pdx.edu:/u/gomenas/Documents/frupal/"


