
dist: trusty

sudo: required

language: node_js

node_js:
  - "node"
  - "9"
  - "8"

cache: node_modules

script:
  - npm run test


# Stand up chromium; set pseudo display; init whatever xvfb is
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
